/*Database creation script
	-version 1.3
	last modified: 19/06/2023
*/

CREATE DATABASE MedKidsDB;
USE MedKidsDB;

CREATE TABLE FUN_FACT(
	id SERIAL PRIMARY KEY,
	fun_fact VARCHAR(250) NOT NULL,
);--1

CREATE TABLE RANK(
	id SERIAL PRIMARY KEY,
	rank VARCHAR(40) NOT NULL DEFAULT 'NEW USER'
);--2

CREATE TABLE PROFILE_PICTURE(
	id SERIAL PRIMARY KEY,
	profile_picture VARCHAR(150) NOT NULL
);--3

CREATE TABLE USER(
	id SERIAL PRIMARY KEY,
	username VARCHAR(40) NOT NULL,
	email VARCHAR(50) NOT NULL,
	password VARCHAR(30) NOT NULL,
	points INT NOT NULL DEFAULT 0,
	profile_picture_id INT NOT NULL DEFAULT 1, --FK
	rank_id INT NOT NULL DEFAULT 1 --FK
);--4

CREATE TABLE LEVEL(
	id SERIAL PRIMARY KEY,
	difficulty INT NOT NULL,
	body_parts_count INT NOT NULL,
);--5

CREATE TABLE BODY_SYSTEM(
	id SERIAL PRIMARY KEY,
	name VARCHAR(25) NOT NULL,
	section_image VARCHAR(150) NOT NULL,
	puzzle_image VARCHAR(150) NOT NULL
);--6

CREATE TABLE LEVELXBODY_SYSTEM(
	level_id INT REFERENCES LEVEL(id),
	body_system INT REFERENCES BODY_SYSTEM(id),
	PRIMARY KEY (level_id, body_system)
);--7


CREATE TABLE INSIGNIA(
	id SERIAL PRIMARY KEY,
	name VARCHAR(35) NOT NULL,
	description VARCHAR(100) NOT NULL,
	image VARCHAR(150) NOT NULL,
	body_system_id INT NOT NULL REFERENCES BODY_SYSTEM(id) --FK
);--8

CREATE TABLE BODY_PART(
	id SERIAL PRIMARY KEY,
	name VARCHAR(30) NOT NULL,
	image varchar(150) NOT NULL,
	description VARCHAR(250)NOT NULL,
	body_system_id INT NOT NULL REFERENCES BODY_SYSTEM(id) --FK
);--9

CREATE TABLE USERXINSIGNIA(
	user_id INT REFERENCES USER(id),
	insignia_id INT REFERENCES INSIGNIA(id),
	PRIMARY KEY (user_id,insignia_id)
);--10