CREATE TABLE LEVELXBODY_SYSTEM(
	id SERIAL PRIMARY KEY,
	level_id INT REFERENCES LEVEL(id),
	body_system INT REFERENCES BODY_SYSTEM(id)
)--6

CREATE TABLE BODY_SYSTEM(
	id SERIAL PRIMARY KEY,
	name VARCHAR(25) NOT NULL,
	section_image VARCHAR(150) NOT NULL,
	puzzle_image VARCHAR(150) NOT NULL
)--7


CREATE TABLE INSIGNIA(
	id SERIAL PRIMARY KEY,
	name VARCHAR(35) NOT NULL,
	description VARCHAR(100) NOT NULL,
	image varchar(150) NOT NULL,
	state BOOL NOT NULL DEFAULT 0,
	body_system_id INT NOT NULL REFERENCES BODY_SYSTEM(id) --FK
)--8

CREATE TABLE BODY_PART(
	id SERIAL PRIMARY KEY,
	name VARCHAR(30) NOT NULL,
	image varchar(150) NOT NULL,
	description VARCHAR(250)NOT NULL,
	body_system_id INT NOT NULL REFERENCES BODY_SYSTEM(id) --FK
)--9

CREATE TABLE USERXINSIGNIA(
	id SERIAL PRIMARY KEY,
	user_id INT REFERENCES USER(id), --
	insignia_id INT REFERENCES INSIGNIA(id)
)--10